tonbo-io/fusio

fusio/src/impls/remotes/http/error.rs
Currently if you create a new project that depends on `fusio` with the `http` feature enabled, you get a compile error:
```
error[E0433]: failed to resolve: use of undeclared crate or module `serde_urlencoded`
--> /Users/aduffy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fusio-0.2.0/src/impls/remotes/http/error.rs:21:23
|
21 |     UrlEncode(#[from] serde_urlencoded::ser::Error),
|                       ^^^^^^^^^^^^^^^^ use of undeclared crate or module `serde_urlencoded`
Compiling h2 v0.4.6
Compiling pyo3-log v0.11.0
For more information about this error, try `rustc --explain E0433`.
error: could not compile `fusio` (lib) due to 1 previous error
```
=> conditional addition of serde_urlencoded error

fusio/src/impls/buffered.rs
Support `BufReader` for converting a large number of continuous reads of small data volumes into a small number of continuous reads of large data volumes
=> feat: impl `BufReader`

.github/workflows/ci.yml, Cargo.toml, fusio-opendal/Cargo.toml, fusio-opendal/README.md, fusio-opendal/src/file.rs, fusio-opendal/src/fs.rs, fusio-opendal/src/lib.rs, fusio-opendal/src/utils.rs, fusio/src/fs/options.rs
Close https://github.com/tonbo-io/fusio/issues/88
=> feat: Add basic layout for fusio-opendal

README.md
Latest opendal will only have `439KB` with default feature enabled:
---
"Comparing to `opendal::Operator`" isn't fair since opendal exposes `opendal::raw::Access`. However, I'm unsure how to improve this statement.
=> docs: Update Compare to OpenDAL

fusio-object-store/src/fs.rs, fusio-opendal/src/fs.rs, fusio/Cargo.toml, fusio/src/dynamic/fs.rs, fusio/src/error.rs, fusio/src/fs/mod.rs, fusio/src/impls/disk/monoio/fs.rs, fusio/src/impls/disk/opfs/fs.rs, fusio/src/impls/disk/tokio/fs.rs, fusio/src/impls/disk/tokio_uring/fs.rs, fusio/src/impls/remotes/aws/fs.rs, fusio/src/impls/remotes/aws/mod.rs, fusio/src/impls/remotes/aws/multipart_upload.rs, fusio/src/impls/remotes/aws/options.rs, fusio/src/impls/remotes/aws/s3.rs, fusio/src/impls/remotes/aws/writer.rs, fusio/src/lib.rs
ref: https://github.com/tonbo-io/fusio/issues/99
=> feat: `Fs` adds `copy` & `link`

fusio/Cargo.toml, fusio/src/impls/disk/opfs/fs.rs, fusio/src/impls/disk/opfs/mod.rs
Fusio can not get `Window` in web worker now, resulting in opfs root directory is not available. This PR make opfs root directory available in web worker
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#web_workers_api
https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/navigator
=> make opfs available in web worker

fusio/src/impls/disk/opfs/fs.rs, fusio/src/impls/disk/opfs/mod.rs
=> docs: add docs for OPFS

fusio/Cargo.toml, fusio/src/impls/remotes/aws/credential.rs, fusio/src/impls/remotes/http/wasm.rs, fusio/tests/wasm_http.rs
- Remove dependency on `std::time` under wasm
- Add missing HTTP headers to `WasmClient`
=> fix: add missing http headers under wasm

.github/workflows/ci.yml, examples/opfs/Cargo.toml, fusio-parquet/Cargo.toml, fusio-parquet/src/reader.rs, fusio-parquet/src/writer.rs, fusio-parquet/tests/wasm.rs, fusio/src/impls/disk/opfs/mod.rs
wrap parquet reader/writer with `Arc<Mutex>` under wasm to make it works on both `OPFSFile` and `S3File`
=> refactor: wrap parquet reader/writer with Arc and Mutex

fusio/Cargo.toml, fusio/src/impls/disk/mod.rs, fusio/src/impls/disk/opfs/fs.rs, fusio/src/impls/disk/opfs/mod.rs, fusio/src/impls/disk/opfs/sync/mod.rs
add support for [FileSystemSyncAccessHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle). 
Known problem: close semantic #113
=> feat: add support for FileSystemSyncAccessHandle

fusio/src/impls/disk/opfs/fs.rs, fusio/tests/opfs.rs
`FileSystemDirectoryHandle::entries` returns all entries under the directory but only includes filenames. We should return the full path like [std::fs::DirEntry](https://doc.rust-lang.org/nightly/std/fs/struct.DirEntry.html#method.path)
=> fix: return full path in opfs list

fusio/src/dynamic/fs.rs, fusio/src/impls/buffered.rs, fusio/src/impls/disk/opfs/sync/mod.rs, fusio/src/impls/disk/tokio/fs.rs, fusio/src/impls/disk/tokio/mod.rs, fusio/src/lib.rs
#113 
change close semantic to not be able to operate after closing
=> refactor: change close semantic for tokio fs and FileSystemSyncAccessHandle

fusio/src/fs/options.rs, fusio/src/impls/disk/monoio/fs.rs, fusio/src/impls/disk/monoio/mod.rs, fusio/src/impls/disk/opfs/fs.rs, fusio/src/impls/disk/opfs/mod.rs, fusio/src/impls/disk/opfs/sync/mod.rs, fusio/src/impls/disk/tokio/fs.rs, fusio/src/impls/disk/tokio_uring/fs.rs, fusio/src/impls/remotes/aws/fs.rs, fusio/src/lib.rs, fusio/tests/opfs.rs
- append to a file instead of overwriting while opening for disk based file(tokio file, opfs, monoio and tokio_uring)
- remove FileHandle struct in OPFS
=> Feat: append to a file instead of overwriting while opening

examples/opfs/Cargo.toml, fusio-object-store/Cargo.toml, fusio-parquet/Cargo.toml
This is needed for TonboDB to upgrade arrow and parquet to 54.
=> chore: bump arrow and parquet to 54

fusio/src/fs/options.rs
I think `OpenOptions::create(bool)` should set write to true only when create is true
=> fix: set write to true only when create is true

fusio/src/dynamic/fs.rs, fusio/src/impls/buffered.rs, fusio/src/impls/disk/tokio/fs.rs, fusio/src/impls/disk/tokio/mod.rs, fusio/src/lib.rs
write will be ignored in append mod, and it will cause error when using `set_len` in windows. So we should manage file position by ourselves.
=> fix: remove append option in tokio

fusio/src/path/mod.rs
- add a `new` method for `Path`, so that user can use `Path::new` to create path under wasm and non-wasm environment
- move `Path::from_opfs_path` to wasm
=> refactor: add `new` method for Path

Cargo.toml, fusio-dispatch/Cargo.toml, fusio-log/Cargo.toml, fusio-object-store/Cargo.toml, fusio-opendal/Cargo.toml, fusio-parquet/Cargo.toml, fusio-parquet/src/reader.rs, fusio/Cargo.toml
- replace `ParquetMetaDataReader::decode_footer` with `ParquetMetaDataReader::decode_footer_tail` due to being deprecated
- bump fusio to 0.3.8
=> bump fusio to 0.3.8

fusio/Cargo.toml, fusio/src/executor/mod.rs, fusio/src/executor/opfs.rs, fusio/src/executor/tokio.rs, fusio/src/lib.rs
- Add executor feature to expose lightweight runtime traits:
- Executor (spawn), JoinHandle (await result), RwLock (async read/write guards).
- Keeps fusio runtime‑agnostic by default; no new deps unless the feature is enabled.
- Designed for optional adapters (e.g., Tokio, WASM) without locking libraries into a single runtime.
Notes
- No behavior change for existing users unless features = ["executor"] is enabled.
- Intended to support non-blocking coordination and pluggable runtimes in higher‑level crates.
=> feat: add executor feature

fusio-manifest/tests/e2e_serializable_isolation.rs, fusio/src/impls/remotes/aws/fs.rs, fusio/src/impls/remotes/aws/head.rs, fusio/src/impls/remotes/aws/multipart_upload.rs, fusio/src/impls/remotes/aws/s3.rs
This PR adds comprehensive end-to-end tests for `fusio-manifest` that validate serializable isolation guarantees against real AWS S3. These tests verify critical distributed consistency properties including transaction isolation, concurrent writer conflicts, and write skew prevention.
Added 6 comprehensive test scenarios:
1. **Basic Write/Read** - Validates fundamental operations
2. **Concurrent Writers Same Key Conflict** - Ensures only one writer succeeds when modifying the same key
3. **Write Skew Prevention** - Validates serializable isolation via HEAD CAS (prevents anomalies even when writing to different keys)
4. **Multi-Writer Chain** - Tests 5 sequential transactions correctly incrementing a counter
5. **Reader During Concurrent Writes** - Verifies snapshot isolation for readers …
=> feat(manifest): add serializable isolation e2e tests

AGENTS.md, examples/src/fs.rs, examples/src/multi_runtime.rs, examples/src/object.rs, examples/src/opendal.rs, examples/src/s3.rs, fusio-manifest/src/checkpoint.rs, fusio-parquet/src/reader.rs, fusio/src/executor/tokio.rs, fusio/src/impls/disk/tokio_uring/fs.rs, fusio/src/impls/mem/fs.rs, fusio/src/impls/remotes/aws/fs.rs, fusio/src/impls/remotes/aws/s3.rs
This PR fixes the clippy command syntax in AGENTS.md and resolves all clippy warnings across the workspace when running `cargo clippy --all-features -- -D warnings`.
- **AGENTS.md**: Fixed clippy command syntax (added `--` before `-D warnings`)
- **AGENTS.md**: Changed British English to US English for consistency (behaviour→behavior, prioritise→prioritize)
- Removed unused `MaybeSend` import
- Fixed `let_and_return` lint by returning expression directly
- Changed `+ Send` to `+ MaybeSend` in `list()` return type to match trait definition
- Added `MaybeSend` import
- Added `#[cfg(not(feature = "no-send"))]` guard for `Executor` impl
- Added `#[cfg_attr(feature = "no-send", allow(dead_code))]` for handle field
- Fixed conditional imports to avoid unused import warnings
- Added …
=> chore: fix clippy command and resolve clippy warnings

docs/fusio-manifest-rfd.md, fusio-manifest/src/lease/mod.rs
Addresses the gap documented in the RFD: "S3 lease contention loop: `S3LeaseStore::create` retries collisions without jitter/backoff or error typing; under S3 throttling the loop will spin and return `PreconditionFailed`, starving readers/writers."
**Core Logic (`fusio-manifest/src/lease/mod.rs`)**
- Replace hardcoded `PreconditionFailed`-only retry with `classify_error()` pattern
- Retry **all** transient errors (S3 throttling, timeouts, network blips) with exponential backoff
- Maintain existing behavior for `PreconditionFailed` (lease name collisions)
- Increment attempt counter before backoff calculation for semantic clarity
**Tests**
- Add `FailingFs` mock to inject transient errors (simulates S3 throttling)
- `lease_first_attempt_success_no_retry_suffix`: validates …
=> fix(manifest): add backoff retry to lease creation for transient errors
